// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelInstall() {
  return window['go']['main']['App']['CancelInstall']();
}

export function CompleteSetup() {
  return window['go']['main']['App']['CompleteSetup']();
}

export function DetectSetupStatus() {
  return window['go']['main']['App']['DetectSetupStatus']();
}

export function ExpandForOnboarding() {
  return window['go']['main']['App']['ExpandForOnboarding']();
}

export function InstallOllama() {
  return window['go']['main']['App']['InstallOllama']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OnCharaClick() {
  return window['go']['main']['App']['OnCharaClick']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetLastEvent(arg1) {
  return window['go']['main']['App']['SetLastEvent'](arg1);
}
