// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {monitor} from '../models';

export function LoadConfig():Promise<config.Config>;

export function OnCharaClick():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetLastEvent(arg1:monitor.MonitorEvent):Promise<void>;
