// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendSpeechHistory(arg1, arg2) {
  return window['go']['main']['App']['AppendSpeechHistory'](arg1, arg2);
}

export function CancelInstall() {
  return window['go']['main']['App']['CancelInstall']();
}

export function CompleteSetup() {
  return window['go']['main']['App']['CompleteSetup']();
}

export function DetectSetupStatus() {
  return window['go']['main']['App']['DetectSetupStatus']();
}

export function ExpandForOnboarding() {
  return window['go']['main']['App']['ExpandForOnboarding']();
}

export function GetContext() {
  return window['go']['main']['App']['GetContext']();
}

export function InstallOllama() {
  return window['go']['main']['App']['InstallOllama']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LogGeminiActivity(arg1) {
  return window['go']['main']['App']['LogGeminiActivity'](arg1);
}

export function OnCharaClick() {
  return window['go']['main']['App']['OnCharaClick']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetClickThrough(arg1) {
  return window['go']['main']['App']['SetClickThrough'](arg1);
}

export function SetLastEvent(arg1) {
  return window['go']['main']['App']['SetLastEvent'](arg1);
}

export function SetMonitor(arg1) {
  return window['go']['main']['App']['SetMonitor'](arg1);
}
