// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';
import {config} from '../models';
import {monitor} from '../models';

export function AppendSpeechHistory(arg1:string,arg2:string):Promise<void>;

export function CancelInstall():Promise<void>;

export function CompleteSetup():Promise<void>;

export function DetectSetupStatus():Promise<main.SetupStatus>;

export function ExpandForOnboarding():Promise<void>;

export function GetContext():Promise<context.Context>;

export function InstallOllama():Promise<void>;

export function LoadConfig():Promise<config.Config>;

export function LogGeminiActivity(arg1:string):Promise<void>;

export function OnCharaClick():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetClickThrough(arg1:boolean):Promise<void>;

export function SetLastEvent(arg1:monitor.MonitorEvent):Promise<void>;

export function SetMonitor(arg1:monitor.Monitor):Promise<void>;
